### ISSUE TITLE
different datasources

### ISSUE THREAD

**Issue by alexdmejias** [udayankumar/cryptoticker#1]
Are you open to using other datasources aside from cryptocompare? I have a local copy that allows the user to choose the data source for the prices (cryptocompare being the default) and instead of adding a fork to the registry I was curious about your opinion on merging it. I added Coinbase but this would open the door to other exchanges.

Edit: Link to fork https://github.com/alexdmejias/cryptoticker

**Comment by alexdmejias** [comment]
@udayankumar Not sure if this got lost in your inbox

**Comment by udayankumar** [comment]
Do you mean data from different exchanges?

**Comment by alexdmejias** [comment]
Yup

**Comment by udayankumar** [comment]
hi @alexdmejias  thank you so much for creating this issue. I have modified this extension to now accept a range of exchanges to get prices from.  Take a look at the readme.

**Comment by alexdmejias** [comment]
👏 nice, much better solution. Thanks
